# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Install Terraform (optional if already available)
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Terraform Init (with remote backend)
- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'backend-storage-conn'
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmStorageAccountName: 'bkendsta111'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.terraform.tfstate'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'backend-storage-conn'

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'backend-storage-conn'